import Fuse from 'fuse.js';
export type Tool = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  website: string;
  icon: string;
  categories: string[];
  useCases: string[];
  targetUsers: string[];
  pricingModel: 'free' | 'freemium' | 'paid' | 'open_source';
  hasFreeTier: boolean;
  startingPriceUsd: number;
  apiAvailable: boolean;
  selfHostable: boolean;
  localRun: boolean;
  dockerSupport: boolean;
  ollamaSupport: boolean;
  openSource: boolean;
  githubUrl?: string;
  githubStars?: number;
  licenseType?: string;
  ossHealthScore: number;
  commitFrequency: 'daily' | 'weekly' | 'monthly' | 'inactive';
  wrapperDepthScore: number;
  trustScore: number;
  affiliateRisk: boolean;
  privacyScore: 'high' | 'medium' | 'low';
  gdprCompliant: boolean;
  dataStored: boolean;
  trainsOnData: boolean;
  matchScore?: number;
  trustWarnings?: string[];
  escapeFrom?: string[];
  monthlyCostUsd?: number;
};

export const tools: Tool[] = [
  {
    id: 'openclaw-ai', slug: 'openclaw', name: 'OpenClaw', icon: '🦖',
    tagline: '2026\'nın en hızlı büyüyen self-host AI assistantı. WhatsApp/Telegram/Discord entegrasyonlu.',
    website: 'https://github.com/openclaw/openclaw',
    categories: ['chatbot', 'automation'], useCases: ['writing', 'coding', 'automation'],
    targetUsers: ['developer', 'enterprise', 'normal'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/openclaw/openclaw', githubStars: 300000,
    licenseType: 'MIT', ossHealthScore: 98, commitFrequency: 'daily',
    wrapperDepthScore: 92, trustScore: 95, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 95,
  },

  // ─── VIDEO ──────────────────────────────────────────────────────────────────
  {
    id: '21', slug: 'runway', name: 'Runway', icon: '🎬',
    tagline: 'Profesyonel AI video üretici. Gen-3 ile sinematik kalite.',
    website: 'https://runwayml.com',
    categories: ['video'], useCases: ['video', 'design'],
    targetUsers: ['creator', 'startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 15,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 78, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 15, trustWarnings: ['Verilerle model eğitiliyor', 'Ücretsiz katmanda watermark'],
  },
  {
    id: '22', slug: 'kling-ai', name: 'Kling AI', icon: '🎥',
    tagline: 'Çince kökenli AI video üretici. Ücretsiz kotası yüksek.',
    website: 'https://klingai.com',
    categories: ['video'], useCases: ['video', 'design'],
    targetUsers: ['creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 80, trustScore: 65, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 10, matchScore: 72,
    trustWarnings: ['Çin sunucuları', 'GDPR uyumlu değil'],
  },
  {
    id: '23', slug: 'heygen', name: 'HeyGen', icon: '🧑‍💼',
    tagline: 'AI avatar ile video üret. Dil dublajı ve avatar klonlama.',
    website: 'https://heygen.com',
    categories: ['video'], useCases: ['video', 'voiceover'],
    targetUsers: ['creator', 'startup', 'enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 29,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 82, trustScore: 74, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 29, trustWarnings: ['Deepfake potansiyeli', 'Pahalı premium plan'],
  },
  {
    id: '24', slug: 'pika-labs', name: 'Pika Labs', icon: '⚡',
    tagline: 'Metin ve görselden kısa AI video. Hızlı ve ücretsiz başlangıç.',
    website: 'https://pika.art',
    categories: ['video'], useCases: ['video', 'design'],
    targetUsers: ['creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 8,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 78, trustScore: 72, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 8, matchScore: 70,
  },

  // ─── MÜZİK / SES ────────────────────────────────────────────────────────────
  {
    id: '25', slug: 'suno', name: 'Suno AI', icon: '🎵',
    tagline: 'Metinden tam şarkı üret. Vokal, enstrüman, prodüksiyon dahil.',
    website: 'https://suno.com',
    categories: ['audio', 'music'], useCases: ['music', 'voiceover'],
    targetUsers: ['creator', 'normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 8,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 90, trustScore: 72, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 8, matchScore: 82,
    trustWarnings: ['Telif hakkı belirsizliği', 'Verilerle model eğitiliyor'],
  },
  {
    id: '26', slug: 'udio', name: 'Udio', icon: '🎶',
    tagline: 'Suno rakibi. Yüksek kaliteli AI müzik üretimi.',
    website: 'https://udio.com',
    categories: ['audio', 'music'], useCases: ['music'],
    targetUsers: ['creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 88, trustScore: 70, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 10, matchScore: 76,
  },
  {
    id: '27', slug: 'whisper', name: 'Whisper (OpenAI)', icon: '🎤',
    tagline: 'Açık kaynak konuşma-metin dönüştürücü. Yerel çalışır, 99 dil.',
    website: 'https://github.com/openai/whisper',
    categories: ['audio'], useCases: ['transcription'],
    targetUsers: ['developer', 'creator', 'normal'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/openai/whisper', githubStars: 78000,
    licenseType: 'MIT', ossHealthScore: 90, commitFrequency: 'monthly',
    wrapperDepthScore: 95, trustScore: 94, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 91,
  },

  // ─── ARAŞTIRMA / SEARCH ──────────────────────────────────────────────────────
  {
    id: '28', slug: 'perplexity', name: 'Perplexity AI', icon: '🔍',
    tagline: 'AI destekli arama motoru. Kaynaklı, hızlı, güncel cevaplar.',
    website: 'https://perplexity.ai',
    categories: ['research', 'chatbot'], useCases: ['research', 'writing'],
    targetUsers: ['normal', 'creator', 'developer', 'student'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 75, trustScore: 80, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '29', slug: 'elicit', name: 'Elicit', icon: '📚',
    tagline: 'Akademik araştırma için AI. Makaleler arası sentez yapar.',
    website: 'https://elicit.com',
    categories: ['research'], useCases: ['research'],
    targetUsers: ['normal', 'student', 'enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 12,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 72, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 80,
  },

  // ─── SUNU / DOKÜMANTASYON ────────────────────────────────────────────────────
  {
    id: '30', slug: 'gamma', name: 'Gamma', icon: '📊',
    tagline: 'Metinden slayt ve sunum üret. PowerPoint öldürücü.',
    website: 'https://gamma.app',
    categories: ['presentation', 'writing'], useCases: ['presentation', 'writing'],
    targetUsers: ['normal', 'creator', 'startup', 'student'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 70, trustScore: 76, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 83,
  },
  {
    id: '31', slug: 'beautiful-ai', name: 'Beautiful.ai', icon: '✨',
    tagline: 'Akıllı sunum tasarımcısı. Tasarım kararlarını otomatik alır.',
    website: 'https://beautiful.ai',
    categories: ['presentation'], useCases: ['presentation', 'design'],
    targetUsers: ['normal', 'startup', 'enterprise'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 12,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 65, trustScore: 70, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 12,
    trustWarnings: ['Ücretsiz katman yok'],
  },

  // ─── YAZARLIK / İÇERİK ──────────────────────────────────────────────────────
  {
    id: '32', slug: 'claude', name: 'Claude (Anthropic)', icon: '🧠',
    tagline: 'Anthropic\'in güvenlik odaklı AI asistanı. Uzun bağlam, derin analiz.',
    website: 'https://claude.ai',
    categories: ['chatbot', 'writing'], useCases: ['writing', 'coding', 'research'],
    targetUsers: ['normal', 'creator', 'developer', 'enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 88, trustScore: 88, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 90,
  },
  {
    id: '33', slug: 'gemini', name: 'Gemini (Google)', icon: '♊',
    tagline: 'Google\'ın çok modlu AI\'ı. Arama entegrasyonu, ücretsiz tier güçlü.',
    website: 'https://gemini.google.com',
    categories: ['chatbot', 'writing'], useCases: ['writing', 'research', 'coding'],
    targetUsers: ['normal', 'creator', 'developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 80, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 84,
    trustWarnings: ['Google hesabıyla bağlantılı', 'Verilerle model eğitilebilir'],
  },
  {
    id: '34', slug: 'jasper', name: 'Jasper AI', icon: '📝',
    tagline: 'Pazarlama ve SEO içeriği için AI yazı aracı.',
    website: 'https://jasper.ai',
    categories: ['writing'], useCases: ['writing', 'marketing'],
    targetUsers: ['creator', 'startup', 'enterprise'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 39,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 55, trustScore: 65, affiliateRisk: true,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 39, escapeFrom: ['jasper'],
    trustWarnings: ['GPT-4 üstü ince wrapper', 'Pahalı', 'Affiliate odaklı'],
  },

  // ─── KOD / GELİŞTİRİCİ ──────────────────────────────────────────────────────
  {
    id: '35', slug: 'bolt-new', name: 'Bolt.new', icon: '⚡',
    tagline: 'Tarayıcıda full-stack uygulama geliştir. Stackblitz tabanlı.',
    website: 'https://bolt.new',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer', 'startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 80, trustScore: 76, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 79,
  },
  {
    id: '36', slug: 'lovable', name: 'Lovable', icon: '💝',
    tagline: 'Doğal dille web uygulaması yaz. React + Supabase otomatik.',
    website: 'https://lovable.dev',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['startup', 'normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 75, trustScore: 74, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 77,
  },
  {
    id: '37', slug: 'ollama', name: 'Ollama', icon: '🦙',
    tagline: 'Yerel LLM çalıştırmanın en kolay yolu. Llama, Mistral, Gemma.',
    website: 'https://ollama.com',
    categories: ['coding', 'chatbot'], useCases: ['coding', 'writing', 'research'],
    targetUsers: ['developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/ollama/ollama', githubStars: 95000,
    licenseType: 'MIT', ossHealthScore: 94, commitFrequency: 'daily',
    wrapperDepthScore: 98, trustScore: 96, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 94,
  },

  // ─── OTOMATİZASYON ──────────────────────────────────────────────────────────
  {
    id: '38', slug: 'make', name: 'Make (Integromat)', icon: '🔁',
    tagline: 'Görsel otomasyon platformu. Zapier\'den daha esnek, daha ucuz.',
    website: 'https://make.com',
    categories: ['automation'], useCases: ['automation'],
    targetUsers: ['normal', 'startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 9,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 72, trustScore: 74, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 9, matchScore: 84, escapeFrom: ['zapier'],
  },

  // ─── GÖRSELLEŞTİRME / VERİ ──────────────────────────────────────────────────
  {
    id: '39', slug: 'julius-ai', name: 'Julius AI', icon: '📈',
    tagline: 'Veri analizi için AI. CSV yükle, grafik çiz, içgörü al.',
    website: 'https://julius.ai',
    categories: ['data', 'research'], useCases: ['research', 'automation'],
    targetUsers: ['normal', 'startup', 'enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 75, trustScore: 78, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 80,
  },

  // ─── EĞİTİM ─────────────────────────────────────────────────────────────────
  {
    id: '40', slug: 'khanmigo', name: 'Khanmigo', icon: '🎓',
    tagline: 'Khan Academy\'nin AI öğretmeni. Cevap vermez, düşündürür.',
    website: 'https://khanacademy.org/khan-labs',
    categories: ['education'], useCases: ['research', 'writing'],
    targetUsers: ['normal', 'student'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 4,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 68, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },

  // ─── MÜŞTERİ HİZMETLERİ ─────────────────────────────────────────────────────
  {
    id: '41', slug: 'tidio', name: 'Tidio', icon: '💬',
    tagline: 'AI chatbot + canlı destek. E-ticaret için güçlü.',
    website: 'https://tidio.com',
    categories: ['automation', 'chatbot'], useCases: ['automation'],
    targetUsers: ['startup', 'enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 29,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 60, trustScore: 72, affiliateRisk: true,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 74,
  },

  // ─── GÖRSEL (YENİ) ──────────────────────────────────────────────────────────
  {
    id: '42', slug: 'ideogram', name: 'Ideogram', icon: '🖋️',
    tagline: 'Metin içeren görseller için en iyi AI. Tipografi mükemmel.',
    website: 'https://ideogram.ai',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator', 'normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 8,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 85, trustScore: 78, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 82,
  },
  {
    id: '43', slug: 'leonardo-ai', name: 'Leonardo AI', icon: '🎭',
    tagline: 'Oyun ve karakter görseli için AI. Fine-tune modeller.',
    website: 'https://leonardo.ai',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator', 'developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 12,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 82, trustScore: 76, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 80,
  },

  {
    id: '1', slug: 'chatgpt', name: 'ChatGPT', icon: '💬',
    tagline: 'OpenAI\'nin güçlü dil modeli. En yaygın AI asistan.',
    website: 'https://chat.openai.com',
    categories: ['chatbot'], useCases: ['writing','coding','research'],
    targetUsers: ['normal','creator','developer','startup','enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 95, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 20, escapeFrom: ['openai'],
  },
  {
    id: '2', slug: 'open-webui', name: 'Open WebUI', icon: '🌐',
    tagline: 'Self-hostable ChatGPT arayüzü — Ollama ile yerel çalışır, tamamen ücretsiz.',
    website: 'https://openwebui.com',
    categories: ['chatbot'], useCases: ['writing','coding','research'],
    targetUsers: ['developer','startup','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/open-webui/open-webui', githubStars: 141000,
    licenseType: 'MIT', ossHealthScore: 91, commitFrequency: 'daily',
    wrapperDepthScore: 88, trustScore: 90, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 91,
  },
  {
    id: '3', slug: 'librechat', name: 'LibreChat', icon: '🗨️',
    tagline: 'Çoklu model desteği, OpenAI API uyumlu, self-host.',
    website: 'https://librechat.ai',
    categories: ['chatbot'], useCases: ['writing','coding','research'],
    targetUsers: ['developer','startup'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/danny-avila/LibreChat', githubStars: 20000,
    licenseType: 'MIT', ossHealthScore: 85, commitFrequency: 'daily',
    wrapperDepthScore: 82, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 87,
  },
  {
    id: '4', slug: 'jan', name: 'Jan', icon: '🦙',
    tagline: 'Tamamen offline çalışan local LLM uygulaması. Privacy-first.',
    website: 'https://jan.ai',
    categories: ['chatbot'], useCases: ['writing','research'],
    targetUsers: ['normal','developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/janhq/jan', githubStars: 24000,
    licenseType: 'AGPL', ossHealthScore: 83, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 92, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 84,
  },
  {
    id: '5', slug: 'cursor', name: 'Cursor', icon: '⌨️',
    tagline: 'AI destekli kod editörü. GitHub Copilot\'tan daha akıllı.',
    website: 'https://cursor.sh',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 70, trustScore: 75, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: false, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 20, escapeFrom: ['cursor'],
    trustWarnings: ['Kapalı kaynak', 'Veriler sunucuda işleniyor'],
  },
  {
    id: '6', slug: 'continue-dev', name: 'Continue.dev', icon: '🔧',
    tagline: 'VS Code ve JetBrains için açık kaynak AI coding asistanı.',
    website: 'https://continue.dev',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: false, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/continuedev/continue', githubStars: 21000,
    licenseType: 'Apache-2.0', ossHealthScore: 88, commitFrequency: 'daily',
    wrapperDepthScore: 90, trustScore: 91, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 89,
  },
  {
    id: '7', slug: 'cline', name: 'Cline', icon: '🤖',
    tagline: 'VS Code için AI coding agent. Çoklu model desteği.',
    website: 'https://github.com/cline/cline',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: false, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/cline/cline', githubStars: 30000,
    licenseType: 'Apache-2.0', ossHealthScore: 87, commitFrequency: 'daily',
    wrapperDepthScore: 88, trustScore: 89, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 83,
  },
  {
    id: '8', slug: 'midjourney', name: 'Midjourney', icon: '🎨',
    tagline: 'En güçlü AI görsel üretici. Discord üzerinden kullanılıyor.',
    website: 'https://midjourney.com',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator','normal'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 80, trustScore: 78, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: false, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 10, escapeFrom: ['adobe','midjourney'],
    trustWarnings: ['Ücretsiz katman yok', 'Verilerle model eğitiliyor', 'Discord bağımlılığı'],
  },
  {
    id: '9', slug: 'stable-diffusion', name: 'Stable Diffusion', icon: '🖼️',
    tagline: 'Açık kaynak görsel üretimi. Yerel çalışır, sınırsız üretim.',
    website: 'https://stability.ai',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator','developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui', githubStars: 145000,
    licenseType: 'AGPL', ossHealthScore: 82, commitFrequency: 'weekly',
    wrapperDepthScore: 95, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '10', slug: 'flux', name: 'Flux', icon: '⚡',
    tagline: 'Yeni nesil açık kaynak görsel modeli. Kalite çok yüksek.',
    website: 'https://blackforestlabs.ai',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator','developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/black-forest-labs/flux', githubStars: 19000,
    licenseType: 'Apache-2.0', ossHealthScore: 85, commitFrequency: 'weekly',
    wrapperDepthScore: 92, trustScore: 86, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '11', slug: 'notion-ai', name: 'Notion AI', icon: '📓',
    tagline: 'Notion\'un yapay zeka eklentisi. Yazma ve özetleme.',
    website: 'https://notion.so',
    categories: ['writing','productivity'], useCases: ['writing','research'],
    targetUsers: ['normal','creator','startup'],
    pricingModel: 'freemium', hasFreeTier: false, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 55, trustScore: 70, affiliateRisk: true,
    privacyScore: 'low', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 10, escapeFrom: ['notion'],
    trustWarnings: ['İnce wrapper (GPT-4 üstü)', 'Ek ücret gerekli', 'Vendor lock-in riski'],
  },
  {
    id: '12', slug: 'obsidian', name: 'Obsidian', icon: '💎',
    tagline: 'Yerel not alma uygulaması. AI eklentileri ile güçlenir.',
    website: 'https://obsidian.md',
    categories: ['writing','productivity'], useCases: ['writing','research'],
    targetUsers: ['normal','creator','developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: false,
    openSource: false, githubStars: 0, ossHealthScore: 75, commitFrequency: 'monthly',
    wrapperDepthScore: 80, trustScore: 85, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 82,
  },
  {
    id: '13', slug: 'github-copilot', name: 'GitHub Copilot', icon: '🐙',
    tagline: 'GitHub\'ın AI kod tamamlayıcısı. Editor\'lara entegre.',
    website: 'https://github.com/features/copilot',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'paid', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 65, trustScore: 72, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 10, escapeFrom: ['github'],
    trustWarnings: ['Microsoft/OpenAI bağımlılığı', 'Kod verileriniz buluta gider'],
  },
  {
    id: '14', slug: 'aider', name: 'Aider', icon: '💡',
    tagline: 'Terminal tabanlı AI coding asistanı. Git entegrasyonu.',
    website: 'https://aider.chat',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: false, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/paul-gauthier/aider', githubStars: 23000,
    licenseType: 'Apache-2.0', ossHealthScore: 84, commitFrequency: 'daily',
    wrapperDepthScore: 86, trustScore: 90, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 80,
  },
  {
    id: '15', slug: 'elevenlabs', name: 'ElevenLabs', icon: '🎙️',
    tagline: 'En gerçekçi AI ses klonlama ve metin-konuşma.',
    website: 'https://elevenlabs.io',
    categories: ['audio'], useCases: ['voiceover'],
    targetUsers: ['creator','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 5,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 78, affiliateRisk: true,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 5, escapeFrom: ['elevenlabs'],
  },
  {
    id: '16', slug: 'coqui-tts', name: 'Coqui TTS', icon: '🐸',
    tagline: 'Açık kaynak metin-konuşma. Yerel çalışır, ücretsiz.',
    website: 'https://coqui.ai',
    categories: ['audio'], useCases: ['voiceover'],
    targetUsers: ['developer','creator'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/coqui-ai/TTS', githubStars: 37000,
    licenseType: 'MPL-2.0', ossHealthScore: 72, commitFrequency: 'monthly',
    wrapperDepthScore: 90, trustScore: 85, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 76,
    trustWarnings: ['Geliştirme yavaşladı — aylık commit'],
  },
  {
    id: '17', slug: 'zapier', name: 'Zapier', icon: '⚡',
    tagline: 'No-code otomasyon platformu. 5000+ uygulama entegrasyonu.',
    website: 'https://zapier.com',
    categories: ['automation'], useCases: ['automation'],
    targetUsers: ['normal','startup','enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 70, trustScore: 72, affiliateRisk: true,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 20, escapeFrom: ['zapier'],
    trustWarnings: ['Pahalı büyüme eğrisi', 'Veri üçüncü taraflardan geçer'],
  },
  {
    id: '18', slug: 'n8n', name: 'n8n', icon: '🔄',
    tagline: 'Self-hostable workflow otomasyonu. Zapier alternatifi, açık kaynak.',
    website: 'https://n8n.io',
    categories: ['automation'], useCases: ['automation'],
    targetUsers: ['developer','startup'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: false, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/n8n-io/n8n', githubStars: 48000,
    licenseType: 'Apache-2.0', ossHealthScore: 90, commitFrequency: 'daily',
    wrapperDepthScore: 88, trustScore: 87, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 90,
  },
  {
    id: '19', slug: 'adobe-firefly', name: 'Adobe Firefly', icon: '🦋',
    tagline: 'Adobe\'nin AI görsel aracı. Creative Cloud entegreli.',
    website: 'https://firefly.adobe.com',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 5,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 75, trustScore: 70, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 5, escapeFrom: ['adobe'],
    trustWarnings: ['Creative Cloud bağımlılığı', 'Verilerle model eğitilir'],
  },
  {
    id: '20', slug: 'comfyui', name: 'ComfyUI', icon: '🎛️',
    tagline: 'Node tabanlı SD arayüzü. Tam kontrol, yerel çalışır.',
    website: 'https://github.com/comfyanonymous/ComfyUI',
    categories: ['image'], useCases: ['design'],
    targetUsers: ['creator','developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/comfyanonymous/ComfyUI', githubStars: 61000,
    licenseType: 'GPL', ossHealthScore: 88, commitFrequency: 'daily',
    wrapperDepthScore: 95, trustScore: 92, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 82,
  },
  // ─── AI ROUTER & AGGREGATOR ────────────────────────────────────────────────
  {
    id: '44', slug: 'openrouter', name: 'OpenRouter', icon: '🔀',
    tagline: '300+ AI modeline tek API. Geliştiriciler için model yönlendirici.',
    website: 'https://openrouter.ai',
    categories: ['router','chatbot'], useCases: ['coding','writing','research'],
    targetUsers: ['developer','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 70, trustScore: 85, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '45', slug: 'poe', name: 'Poe', icon: '💎',
    tagline: 'Quora\'nun çoklu model platformu. 100+ AI modeli tek yerde.',
    website: 'https://poe.com',
    categories: ['router','chatbot'], useCases: ['writing','research','coding'],
    targetUsers: ['normal','creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 45, trustScore: 75, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 78, trustWarnings: ['Veriler Quora sunucularında saklanır'],
  },
  {
    id: '46', slug: 'typingmind', name: 'TypingMind', icon: '⌨️',
    tagline: 'Kendi API anahtarınla çalışan AI arayüzü. BYOK — tam kontrol sende.',
    website: 'https://www.typingmind.com',
    categories: ['router','chatbot'], useCases: ['writing','coding','research'],
    targetUsers: ['developer','creator'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 39,
    apiAvailable: false, selfHostable: true, localRun: false, dockerSupport: false, ollamaSupport: true,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 60, trustScore: 82, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 80,
  },
  {
    id: '47', slug: 'litellm', name: 'LiteLLM', icon: '🔌',
    tagline: 'Açık kaynak AI model yönlendirici. 100+ modele tek API gateway.',
    website: 'https://litellm.ai',
    categories: ['router','automation'], useCases: ['coding','automation'],
    targetUsers: ['developer','startup','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/BerriAI/litellm', githubStars: 16000,
    licenseType: 'MIT', ossHealthScore: 90, commitFrequency: 'daily',
    wrapperDepthScore: 75, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  // ─── YEREL LLM ─────────────────────────────────────────────────────────────
  {
    id: '48', slug: 'lm-studio', name: 'LM Studio', icon: '🖥️',
    tagline: 'En kolay yerel LLM arayüzü. İndir, çalıştır, konuş — internet yok.',
    website: 'https://lmstudio.ai',
    categories: ['chatbot'], useCases: ['writing','coding','research'],
    targetUsers: ['normal','developer','creator'],
    pricingModel: 'free', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 80, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 90,
  },
  {
    id: '49', slug: 'gpt4all', name: 'GPT4All', icon: '🤖',
    tagline: 'Açık kaynak yerel chatbot. Düşük donanımda bile çalışır.',
    website: 'https://gpt4all.io',
    categories: ['chatbot'], useCases: ['writing','research'],
    targetUsers: ['normal','developer'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/nomic-ai/gpt4all', githubStars: 72000,
    licenseType: 'MIT', ossHealthScore: 85, commitFrequency: 'weekly',
    wrapperDepthScore: 82, trustScore: 90, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '50', slug: 'msty', name: 'Msty', icon: '✨',
    tagline: 'Şık workspace arayüzlü yerel LLM. Ollama + bulut modelleri birlikte.',
    website: 'https://msty.app',
    categories: ['chatbot'], useCases: ['writing','research','coding'],
    targetUsers: ['normal','creator'],
    pricingModel: 'free', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: true,
    openSource: false, ossHealthScore: 0, commitFrequency: 'weekly',
    wrapperDepthScore: 72, trustScore: 80, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 82,
  },
  {
    id: '51', slug: 'anythingllm', name: 'AnythingLLM', icon: '📂',
    tagline: 'Kendi dokümanlarınla konuşan AI. Yerel RAG sistemi.',
    website: 'https://anythingllm.com',
    categories: ['chatbot','research'], useCases: ['research','writing'],
    targetUsers: ['developer','startup','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/Mintplex-Labs/anything-llm', githubStars: 30000,
    licenseType: 'MIT', ossHealthScore: 88, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 86,
  },
  {
    id: '52', slug: 'private-gpt', name: 'PrivateGPT', icon: '🔐',
    tagline: 'Tamamen gizli, yerel RAG. Şirket verilerin asla dışarı çıkmaz.',
    website: 'https://privategpt.dev',
    categories: ['chatbot','research'], useCases: ['research','writing'],
    targetUsers: ['developer','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: true,
    openSource: true, githubUrl: 'https://github.com/zylon-ai/private-gpt', githubStars: 55000,
    licenseType: 'Apache-2.0', ossHealthScore: 85, commitFrequency: 'weekly',
    wrapperDepthScore: 90, trustScore: 92, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '53', slug: 'localai', name: 'LocalAI', icon: '🏠',
    tagline: 'OpenAI API uyumlu yerel motor. Drop-in replacement.',
    website: 'https://localai.io',
    categories: ['chatbot','automation'], useCases: ['coding','automation'],
    targetUsers: ['developer','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/mudler/LocalAI', githubStars: 28000,
    licenseType: 'MIT', ossHealthScore: 82, commitFrequency: 'daily',
    wrapperDepthScore: 88, trustScore: 86, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 83,
  },
  // ─── CODING AGENTS ─────────────────────────────────────────────────────────
  {
    id: '54', slug: 'windsurf', name: 'Windsurf', icon: '🏄',
    tagline: 'AI-native IDE. Cascade agent ile otonom kod yazımı.',
    website: 'https://codeium.com/windsurf',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 85, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '55', slug: 'claude-code', name: 'Claude Code', icon: '🧠',
    tagline: 'Terminal bazlı coding agent. Derin analiz ve refactoring ustası.',
    website: 'https://docs.anthropic.com/en/docs/claude-code',
    categories: ['coding'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 95, trustScore: 90, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 20, matchScore: 90,
  },
  {
    id: '56', slug: 'devin', name: 'Devin', icon: '🤖',
    tagline: 'Otonom AI yazılım mühendisi. Planlama, kodlama, test — tek başına.',
    website: 'https://devin.ai',
    categories: ['coding','agent'], useCases: ['coding'],
    targetUsers: ['developer','startup','enterprise'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 500,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 95, trustScore: 78, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 500, matchScore: 82,
  },
  {
    id: '57', slug: 'replit-agent', name: 'Replit Agent', icon: '⚡',
    tagline: 'Prompt\'tan deploy\'a. Bulutta anında uygulama oluştur.',
    website: 'https://replit.com',
    categories: ['coding','agent'], useCases: ['coding'],
    targetUsers: ['normal','creator','developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'daily',
    wrapperDepthScore: 80, trustScore: 78, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 80,
    trustWarnings: ['Kodunuz Replit sunucularında saklanır ve AI eğitiminde kullanılabilir'],
  },
  // ─── TASARIM & UI ────────────────────────────────────────────────────────
  {
    id: '58', slug: 'canva-ai', name: 'Canva AI', icon: '✨',
    tagline: 'Herkes için yapay zeka destekli tasarım. Magic Studio.',
    website: 'https://canva.com',
    categories: ['design','image'], useCases: ['design','writing'],
    targetUsers: ['normal','creator','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 15,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 60, trustScore: 88, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '59', slug: 'figma-ai', name: 'Figma AI', icon: '🎨',
    tagline: 'UI/UX tasarımcıları için yerleşik AI araçları.',
    website: 'https://figma.com',
    categories: ['design'], useCases: ['design'],
    targetUsers: ['creator','developer','enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 15,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 70, trustScore: 90, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '60', slug: 'recraft', name: 'Recraft', icon: '📐',
    tagline: 'Profesyonel AI vektör ve ikon üretici. Sınırsız varyasyon.',
    website: 'https://recraft.ai',
    categories: ['design','image'], useCases: ['design'],
    targetUsers: ['creator','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 20,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 85, trustScore: 84, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 82,
  },
  {
    id: '61', slug: 'krea-ai', name: 'Krea AI', icon: '🪄',
    tagline: 'Gerçek zamanlı görsel üretim ve upscale aracı.',
    website: 'https://krea.ai',
    categories: ['design','image'], useCases: ['design'],
    targetUsers: ['creator','normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 30,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 80, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 84,
  },
  // ─── ÇEVİRİ ──────────────────────────────────────────────────────────────
  {
    id: '62', slug: 'deepl', name: 'DeepL', icon: '🌐',
    tagline: 'Dünyanın en doğru AI çeviri motoru. Avrupa dillerinde rakipsiz.',
    website: 'https://deepl.com',
    categories: ['translation','writing'], useCases: ['writing','research'],
    targetUsers: ['normal','startup','enterprise'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 9,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 95, trustScore: 95, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 92,
  },
  {
    id: '63', slug: 'immersive-translate', name: 'Immersive Translate', icon: '🌍',
    tagline: 'Çift dilli tarayıcı uzantısı. PDF ve YouTube videolarını anında çevir.',
    website: 'https://immersivetranslate.com',
    categories: ['translation'], useCases: ['research','reading'],
    targetUsers: ['normal','creator','developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 8,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 80, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 86,
  },
  // ─── VİDEO DÜZENLEME & AVATAR ────────────────────────────────────────────
  {
    id: '64', slug: 'capcut-ai', name: 'CapCut AI', icon: '✂️',
    tagline: 'Ücretsiz AI video düzenleyici. Otomatik altyazı ve efektler.',
    website: 'https://capcut.com',
    categories: ['video','design'], useCases: ['video'],
    targetUsers: ['creator','normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 70, trustScore: 85, affiliateRisk: false,
    privacyScore: 'low', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 80,
    trustWarnings: ['ByteDance verilerinizi analiz edebilir'],
  },
  {
    id: '65', slug: 'synthesia', name: 'Synthesia', icon: '🗣️',
    tagline: 'Kurumsal kalitede AI avatar ile video üretimi.',
    website: 'https://synthesia.io',
    categories: ['video'], useCases: ['video','presentation'],
    targetUsers: ['startup','enterprise'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 22,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 90, trustScore: 92, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 84,
  },
  // ─── VERİMLİLİK & DİĞER AGENT'LAR ────────────────────────────────────────
  {
    id: '66', slug: 'raycast-ai', name: 'Raycast AI', icon: '🔍',
    tagline: 'macOS için ışık hızında AI asistan ve başlatıcı.',
    website: 'https://raycast.com',
    categories: ['productivity','chatbot'], useCases: ['writing','coding'],
    targetUsers: ['developer','creator'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 80, trustScore: 95, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 88,
  },
  {
    id: '67', slug: 'pieces', name: 'Pieces', icon: '🧩',
    tagline: 'Geliştiriciler için snippet yöneticisi ve yerel AI asistan.',
    website: 'https://pieces.app',
    categories: ['coding','productivity'], useCases: ['coding'],
    targetUsers: ['developer'],
    pricingModel: 'free', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: true, dockerSupport: false, ollamaSupport: true,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 85, trustScore: 88, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '68', slug: 'copilot-workspace', name: 'Copilot Workspace', icon: '🛠️',
    tagline: 'GitHub\'ın task odaklı otonom kod geliştirme ortamı.',
    website: 'https://copilot-workspace.githubnext.com',
    categories: ['coding','agent'], useCases: ['coding'],
    targetUsers: ['developer','enterprise'],
    pricingModel: 'paid', hasFreeTier: false, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 85, trustScore: 92, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 86,
  },
  // ─── 3D & DİĞERLERİ ──────────────────────────────────────────────────────
  {
    id: '69', slug: 'tripo-ai', name: 'Tripo AI', icon: '🧊',
    tagline: 'Metinden veya görselden saniyeler içinde 3D model üret.',
    website: 'https://tripo3d.ai',
    categories: ['3d','design'], useCases: ['design','video'],
    targetUsers: ['creator','developer'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 15,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 85, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 80,
  },
  {
    id: '70', slug: 'luma-ai', name: 'Luma AI', icon: '🌌',
    tagline: 'NeRF teknolojisi ile telefonunuzdan profesyonel 3D sahneler oluşturun.',
    website: 'https://lumalabs.ai',
    categories: ['3d','video'], useCases: ['video','design'],
    targetUsers: ['creator','normal'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 90, trustScore: 88, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '71', slug: 'rask-ai', name: 'Rask AI', icon: '🎙️',
    tagline: 'Videoları dudak senkronu ile 130+ dile otomatik dublaj yapın.',
    website: 'https://rask.ai',
    categories: ['video','translation','audio'], useCases: ['video','translation'],
    targetUsers: ['creator','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 49,
    apiAvailable: true, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 75, trustScore: 85, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 84,
  },
  {
    id: '72', slug: 'mem', name: 'Mem', icon: '📝',
    tagline: 'Kendiliğinden organize olan AI destekli not defteri.',
    website: 'https://mem.ai',
    categories: ['productivity','writing'], useCases: ['writing','research'],
    targetUsers: ['normal','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 10,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 80, trustScore: 82, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 85,
  },
  {
    id: '73', slug: 'kittl', name: 'Kittl', icon: '🖋️',
    tagline: 'Gelişmiş tipografi ve AI destekli tasarım platformu.',
    website: 'https://kittl.com',
    categories: ['design'], useCases: ['design'],
    targetUsers: ['creator','startup'],
    pricingModel: 'freemium', hasFreeTier: true, startingPriceUsd: 15,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 75, trustScore: 85, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 82,
  },
  {
    id: '74', slug: 'microsoft-designer', name: 'Microsoft Designer', icon: '🖌️',
    tagline: 'DALL-E destekli sosyal medya görseli ve tasarım oluşturucu.',
    website: 'https://designer.microsoft.com',
    categories: ['design','image'], useCases: ['design'],
    targetUsers: ['normal','creator'],
    pricingModel: 'free', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: false, selfHostable: false, localRun: false, dockerSupport: false, ollamaSupport: false,
    openSource: false, ossHealthScore: 0, commitFrequency: 'inactive',
    wrapperDepthScore: 65, trustScore: 90, affiliateRisk: false,
    privacyScore: 'medium', gdprCompliant: true, dataStored: true, trainsOnData: true,
    monthlyCostUsd: 0, matchScore: 86,
  },
  {
    id: '75', slug: 'bifrost', name: 'Bifrost', icon: '🌉',
    tagline: 'Maxim AI\'ın açık kaynaklı, yüksek performanslı AI model gateway\'i.',
    website: 'https://getmaxim.ai',
    categories: ['router'], useCases: ['coding','automation'],
    targetUsers: ['developer','enterprise'],
    pricingModel: 'open_source', hasFreeTier: true, startingPriceUsd: 0,
    apiAvailable: true, selfHostable: true, localRun: true, dockerSupport: true, ollamaSupport: false,
    openSource: true, githubUrl: 'https://github.com/maxim-ai/bifrost', githubStars: 1200,
    licenseType: 'MIT', ossHealthScore: 85, commitFrequency: 'weekly',
    wrapperDepthScore: 88, trustScore: 84, affiliateRisk: false,
    privacyScore: 'high', gdprCompliant: true, dataStored: false, trainsOnData: false,
    monthlyCostUsd: 0, matchScore: 82,
  },
];

export const stackPresets = [
  {
    id: 'student',
    name: 'Öğrenci Stack',
    icon: '🎓',
    description: 'Sıfır bütçeyle maksimum güç. Tüm araçlar ücretsiz.',
    totalMonthlyCost: 0,
    tools: ['open-webui', 'continue-dev', 'stable-diffusion', 'obsidian', 'n8n'],
  },
  {
    id: 'solo-founder',
    name: 'Solo Kurucu Stack',
    icon: '🚀',
    description: 'Tek başına bir şirket gibi çalış. Minimum maliyet, maksimum verim.',
    totalMonthlyCost: 5,
    tools: ['open-webui', 'cursor', 'flux', 'n8n', 'obsidian'],
  },
  {
    id: 'youtube-automation',
    name: 'YouTube Otomasyon Stack',
    icon: '🎬',
    description: 'Script, ses, görsel — hepsini AI ile otomatize et.',
    totalMonthlyCost: 0,
    tools: ['open-webui', 'coqui-tts', 'stable-diffusion', 'n8n'],
  },
  {
    id: 'privacy-first',
    name: 'Privacy-First Stack',
    icon: '🔒',
    description: 'Hiçbir verin buluta gitmesin. Tamamen yerel, tamamen özgür.',
    totalMonthlyCost: 0,
    tools: ['jan', 'aider', 'stable-diffusion', 'obsidian'],
  },
  {
    id: 'low-end-laptop',
    name: 'Düşük Donanım Stack',
    icon: '💻',
    description: 'Eski veya zayıf bilgisayarda bile çalışır.',
    totalMonthlyCost: 0,
    tools: ['open-webui', 'continue-dev', 'obsidian'],
  },
];

export const escapeModes = [
  { id: 'openai', name: 'Escape OpenAI', icon: '🏴', color: '#6366F1', fromCost: 72, toCost: 3 },
  { id: 'adobe', name: 'Escape Adobe', icon: '🎨', color: '#E85D4A', fromCost: 55, toCost: 0 },
  { id: 'zapier', name: 'Escape Zapier', icon: '⚡', color: '#F59E0B', fromCost: 50, toCost: 0 },
  { id: 'notion', name: 'Escape Notion', icon: '📓', color: '#18181B', fromCost: 20, toCost: 0 },
  { id: 'github', name: 'Escape GitHub Copilot', icon: '🐙', color: '#374151', fromCost: 10, toCost: 0 },
];



// Pre-build dictionaries for O(1) lookups
const toolsBySlug = new Map<string, Tool>(tools.map(t => [t.slug, t]));
const toolsById = new Map<string, Tool>(tools.map(t => [t.id, t]));

export function getToolBySlug(slug: string): Tool | undefined {
  return toolsBySlug.get(slug);
}

export function getToolById(id: string): Tool | undefined {
  return toolsById.get(id);
}

export function getAlternatives(slug: string, limit = 5): Tool[] {
  const source = getToolBySlug(slug);
  if (!source) return [];
  return tools
    .filter(t => t.slug !== slug && t.categories.some(c => source.categories.includes(c)))
    .sort((a, b) => (b.matchScore ?? 0) - (a.matchScore ?? 0))
    .slice(0, limit);
}


export function searchTools(query: string): Tool[] {
  if (!query || query.trim() === '') return tools;

  // 1. Türkçe karakter ve noktalama normalizasyonu
  const normalize = (str: string) => str.toLowerCase()
    .replace(/ğ/g, 'g').replace(/ü/g, 'u').replace(/ş/g, 's')
    .replace(/ı/g, 'i').replace(/ö/g, 'o').replace(/ç/g, 'c')
    .replace(/[^a-z0-9\s]/g, '');

  const qNorm = normalize(query);
  const qWords = qNorm.split(/\s+/).filter(w => w.length > 1);

  // 2. Eşanlamlı Kelimeler Sözlüğü (Synonyms)
  const synonyms: Record<string, string[]> = {
    'ai': ['yapay zeka', 'yapayzeka'],
    'resim': ['image', 'gorsel', 'fotograf', 'foto', 'cizim'],
    'video': ['animasyon', 'film', 'kurgu'],
    'yazi': ['writing', 'yazarlik', 'metin', 'makale', 'blog', 'icerik'],
    'kod': ['coding', 'yazilim', 'gelistirme', 'programlama', 'yazılımcı'],
    'ses': ['audio', 'muzik', 'dublaj', 'voice', 'sarki'],
    'sunum': ['presentation', 'slayt', 'powerpoint'],
    'bedava': ['free', 'ucretsiz', 'parasiz'],
    'chat': ['chatbot', 'sohbet', 'konusma'],
    '3d': ['model', 'ucboyutlu'],
    'cevir': ['translation', 'ceviri', 'tercume', 'altyazi'],
  };

  // Sorgudaki kelimelerin eşanlamlılarını bul
  let expandedTerms = [...qWords];
  qWords.forEach(word => {
    Object.entries(synonyms).forEach(([key, values]) => {
      if (word === key || values.includes(word)) {
        expandedTerms.push(key, ...values);
      }
    });
  });

  // Benzersiz arama terimleri (tekrarları temizle)
  expandedTerms = Array.from(new Set(expandedTerms));
  const expandedQuery = expandedTerms.join(' ');

  // 3. Fuse.js ile Fuzzy Search
  // Prepare data with normalized fields for better matching
  const fuseData = tools.map(tool => ({
    ...tool,
    normalizedName: normalize(tool.name),
    normalizedTagline: normalize(tool.tagline),
    normalizedCategories: tool.categories.map(c => normalize(c)),
    normalizedUseCases: tool.useCases.map(u => normalize(u)),
  }));

  const fuse = new Fuse(fuseData, {
    keys: [
      { name: 'normalizedName', weight: 0.5 },
      { name: 'normalizedCategories', weight: 0.2 },
      { name: 'normalizedUseCases', weight: 0.2 },
      { name: 'normalizedTagline', weight: 0.1 }
    ],
    threshold: 0.4, // Lower threshold = more strict, higher = more fuzzy
    ignoreLocation: true,
    includeScore: true
  });

  const fuseResults = fuse.search(expandedQuery);

  // Extract tools and apply custom boosting
  const results = fuseResults.map(result => {
    const item = result.item;
    let score = (1 - (result.score || 0)) * 100; // Invert score so higher is better

    const isFree = item.pricingModel === 'free' || item.pricingModel === 'open_source' || item.hasFreeTier;
    if ((expandedTerms.includes('free') || expandedTerms.includes('ucretsiz')) && isFree) {
      score += 40;
    }

    // Original tool without normalized fields
    const tool = getToolById(item.id) as Tool;
    return { tool, score };
  });

  // Sırala ve döndür
  return results
    .sort((a, b) => b.score - a.score)
    .map(r => r.tool);
}
