import type { Tool } from '@/lib/tools';

export const METRICS: { key: keyof Tool; label: string; icon: string; render: (v: unknown) => string; good?: (v: unknown) => boolean }[] = [
  { key: 'pricingModel',      label: 'Fiyat Modeli',      icon: '💳',
    render: v => ({ free: 'Ücretsiz', freemium: 'Freemium', paid: 'Ücretli', open_source: 'Açık Kaynak' }[v as string] ?? String(v)),
    good: v => v === 'free' || v === 'open_source' },
  { key: 'startingPriceUsd', label: 'Başlangıç Fiyatı',  icon: '💰',
    render: v => v === 0 ? 'Ücretsiz' : `$${v}/ay`,
    good: v => v === 0 },
  { key: 'trustScore',       label: 'Güven Puanı',        icon: '🛡️',
    render: v => `${v}/100`,
    good: v => (v as number) >= 85 },
  { key: 'privacyScore',     label: 'Gizlilik',           icon: '🔒',
    render: v => ({ high: '🟢 Yüksek', medium: '🟡 Orta', low: '🔴 Düşük' }[v as string] ?? String(v)),
    good: v => v === 'high' },
  { key: 'gdprCompliant',    label: 'GDPR Uyumlu',        icon: '🇪🇺',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'trainsOnData',     label: 'Verinizle Eğitiyor', icon: '⚠️',
    render: v => v ? '❌ Evet' : '✅ Hayır',
    good: v => !v },
  { key: 'dataStored',       label: 'Veri Depolama',      icon: '💾',
    render: v => v ? '❌ Sunucuda' : '✅ Hayır',
    good: v => !v },
  { key: 'openSource',       label: 'Açık Kaynak',        icon: '📖',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'localRun',         label: 'Yerel Çalışır',      icon: '🖥️',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'selfHostable',     label: 'Self-Host',          icon: '🏠',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'apiAvailable',     label: 'API Mevcut',         icon: '🔌',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'dockerSupport',    label: 'Docker Desteği',     icon: '🐳',
    render: v => v ? '✅ Evet' : '❌ Hayır',
    good: v => !!v },
  { key: 'ossHealthScore',   label: 'OSS Sağlık Puanı',  icon: '💚',
    render: v => (v as number) > 0 ? `${v}/100` : 'Kapalı kaynak',
    good: v => (v as number) >= 80 },
  { key: 'wrapperDepthScore',label: 'Wrapper Derinliği',  icon: '📦',
    render: v => `${v}/100 ${(v as number) >= 85 ? '(Orijinal)' : '(Wrapper)'}`,
    good: v => (v as number) >= 80 },
  { key: 'affiliateRisk',    label: 'Affiliate Riski',    icon: '🚩',
    render: v => v ? '❌ Var' : '✅ Yok',
    good: v => !v },
];
